#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
	/data

# create symlinks
ln -s /var/www/html /data

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
	echo '[services.d] done.'
fi

# set permissions
chown -R abc:abc \
	/data \
	/config \
	/var/www/
