#!/usr/bin/with-contenv bash

# download
is_empty_dir(){ 
	return `ls -A $1|wc -w`
}
if is_empty_dir '/data'; then
	if [ -z ${DIRECTORYLISTER_RELEASE+x} ]; then
		DIRECTORYLISTER_RELEASE=$(curl -sX GET "https://api.github.com/repos/stuarthua/directorylister/releases/latest"	| awk '/tag_name/{print $4;exit}' FS='[""]');
	fi
	curl -o /tmp/directorylister.tar.gz -L "https://github.com/stuarthua/directorylister/archive/${DIRECTORYLISTER_RELEASE}.tar.gz"
	tar xf /tmp/directorylister.tar.gz -C /data/ --strip-components=1
	rm -rf /tmp/*
fi

# create directory structure
mkdir -p \
	/var/www

# create symlinks
ln -s /data /var/www/html

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
	echo '[services.d] done.'
fi

# set permissions
chown -R abc:abc \
	/data \
	/config \
	/var/www/
